export const actNowContent = {
  title: "SDG Act Now",
  subtitle: "To preserve a liveable climate, the average emissions per person per year will need to drop to around 2 tons of CO₂e by 2030. The UN's SDGs provide guidance to meet this target, starting with the Ten Actions to help tackle the climate crisis.",
  carbonFootprint: "As Britannica Editors (2026) note, carbon dioxide is the most significant greenhouse gas linked to global warming. A carbon footprint refers to the total amount of greenhouse gases — primarily carbon dioxide — emitted by an individual, product, or activity. Carbon dioxide is commonly measured in CO₂e (carbon dioxide equivalent), capturing both direct and indirect emissions (Carbon expert, 2026). Direct emissions come from driving cars, using electricity, cooking, and heating, while indirect emissions arise from using paper, stationery, and consuming food (Green.Earth, n.d.). Calculating and reducing one's carbon footprint is an integral part of fulfilling our climate goals.",
  actions: [
    {
      member: "Janet (Yuheng Hou)",
      sdg: "SDG 13",
      action: "Walk, bike, or take public transport",
      image: "/images/sdg13/image7.jpg",
      imageCaption: "Source: ECO Reside — Environmental Benefits Of Public Transportation",
      explanation: "The world's roadways are clogged with vehicles, most of them burning diesel or gasoline. Walking or riding a bike instead of driving will reduce greenhouse gas emissions — and help your health and fitness. For longer distances, consider taking a train or bus. And carpool whenever possible. Living car-free can reduce your carbon footprint by up to 2 tons of CO₂e per year compared to a lifestyle using a car (Nations, n.d.).",
      mechanism: "The core mechanism by which adopting walking, biking, or taking public transport reduces emissions is that these low-carbon or zero-carbon travel modes replace individual travel powered by fossil fuels, primarily gasoline or diesel vehicles. Walking and biking produce no direct emissions at all, while public transport can significantly cut per capita carbon emissions due to its higher passenger capacity per unit of energy consumed. The carbon footprint of bikes mainly comes from manufacturing and maintenance, averaging about 5 grams of CO₂ per kilometer. In contrast, a diesel bus emits around 101 grams of CO₂ per passenger per kilometer (FasterCapital, 2025).",
      example: "For daily commutes to work or school, prioritize public transport options such as subway and bus instead of private car. For short-distance trips, such as grocery shopping at the supermarket near your residence, attending a gathering with friends in the neighborhood, or studying at a nearby library, choose walking or biking directly. This approach not only allows you to flexibly avoid congested road sections, but also reduces carbon emissions.",
      calculator: {
        description: "Using the United Nations online platform for voluntary cancellation of certified emission reductions (CERs), the annual carbon emission of a representative household was calculated and analyzed.",
        calculatorImage: "/images/sdg13/image9.png",
        screenshots: Array.from({ length: 10 }, (_, i) => `/images/sdg13/image${i + 8}.png`),
        before: {
          total: "22.96",
          perCapita: "5.74",
          details: "Based on a four-member household, the per capita annual carbon emission is approximately 5.74 tons of CO₂e. Although this figure is lower than the average level of Chinese households, it is still far higher than the per capita target of 2 tons of CO₂e by 2030 proposed by the United Nations, reaching nearly three times the target value. From the perspective of emission structure, food consumption accounts for the largest proportion, while transportation accounts for 26%, which mainly comes from the use of private cars.",
        },
        after: {
          total: "19.05",
          perCapita: "4.76",
          details: "After the implementation of the initiative, the household annual carbon emission reaches 19.05 tons of CO₂e, with a per capita emission of 4.76 tons — a reduction of approximately one ton compared to before, demonstrating significant results. This transportation emission reduction measure proves to be an effective solution.",
        },
      },
      coBenefits: [
        { title: "Ease Traffic Congestion", desc: "Reducing the use of private vehicles can lower vehicle density on urban roads, effectively alleviate commuting congestion during peak hours, and improve the operational efficiency of transportation systems." },
        { title: "Improve Physical & Mental Health", desc: "Regularly walking or biking for a certain distance every day can effectively enhance cardiovascular function and reduce the risk of diseases such as obesity and hypertension. Moreover, increasing the duration of outdoor activities can alleviate daily stress and improve mental health." },
        { title: "Reduce Economic Expenditure", desc: "Opting for public transport, walking, or biking can eliminate multiple expenditures associated with private car use, including fuel costs, parking fees, and insurance, thereby reducing living burdens." },
        { title: "Optimize the Ecological Environment", desc: "Mitigation of traffic congestion and reduction of private vehicle usage can further lower urban noise pollution and exhaust emission pollution, thereby improving both residents' living quality and urban air quality (Hodges, 2025)." },
        { title: "Ensure National Energy Security", desc: "As private car usage decreases, fuel consumption also declines accordingly. This can reduce the country's dependence on petroleum imports, mitigate the geopolitical risks associated with energy supply, while creating greater space for energy structure transition." },
      ],
      offsetSolutions: [
        {
          title: "Shift weekly commute kilometres to transit and retire verified credits",
          desc: "For unavoidable trips that still create emissions, I would record the remaining transport footprint each month and purchase verified carbon credits through a credible platform, prioritising public-transport or renewable-energy projects that avoid equivalent CO2e elsewhere.",
          evidence: "Add a member head shot on public transport or holding a transit card.",
        },
        {
          title: "Fund urban tree planting near transport corridors",
          desc: "A practical offset is to support verified urban greening or reforestation programmes. This compensates for remaining commute emissions while improving shade, urban heat resilience, and local air quality around roads.",
          evidence: "Add a member head shot beside a planted tree or local greening site.",
        },
        {
          title: "Support renewable electricity for stations and homes",
          desc: "Transport choices are cleaner when electricity and shared infrastructure use lower-carbon power. I would offset residual emissions by supporting renewable-energy certificates or local clean-energy programmes connected to daily travel and household charging needs.",
          evidence: "Add a member head shot with a renewable-energy bill, app, or station display.",
        },
      ],
    },
    {
      member: "Janet (Yuheng Hou)",
      sdg: "SDG 4",
      action: "Reduce, reuse, repair, recycle",
      image: "/images/sdg4/image9.png",
      imageCaption: "Source: Visual China Group — Carbon footprint distribution",
      explanation: "Electronics, clothes, plastics and other items we buy cause carbon emissions at each point in production, from the extraction of raw materials to manufacturing and transporting goods to market. To protect the climate, buy fewer things, shop second-hand, and repair what you can. Plastics alone generated 1.8 billion metric tons of greenhouse gas emissions in 2019 — 3.4 per cent of the global total. Less than 10 per cent is recycled, and once plastic is discarded, it can linger for hundreds of years. Every kilogram of textiles produced generates about 17 kilograms of CO₂e (United Nations, n.d.).",
      mechanism: "The 4R action reduces greenhouse gas emissions by targeting every stage in the lifecycle of products. Every product generates emissions throughout its lifecycle, involving raw material extraction, manufacturing, transporting, and disposal. By diminishing unnecessary consumption, we cut down production, avoiding carbon emissions. Reusing items lengthens their lifespan, eliminating the need for new production. Repairing extends product life further. Recycling diverts materials back into production cycles, which uses far less energy than producing from virgin materials (Scells et al., 2022). Together, these actions break the conventional product lifecycle, realising measurable reductions in emissions.",
      example: "In daily life, the 4R approach works as follows: bring a reusable water bottle to reduce disposable items; use second-hand textbooks and stationery whenever possible; mend torn clothes and repair broken books instead of buying replacements; categorise paper, plastic, and metal waste for proper recycling. This lifestyle not only contributes to a more affordable and sustainable way of living, but also plays an essential role in reducing carbon emissions.",
      calculator: {
        description: "Using the United Nations online platform for voluntary cancellation of certified emission reductions (CERs), the annual carbon footprint of a representative household was calculated. Food and transportation account for 43% and 34% of emissions respectively — the two largest contributors.",
        screenshots: Array.from({ length: 15 }, (_, i) => `/images/sdg4/image${i + 10}.png`),
        before: {
          total: "41.12",
          perCapita: "8.22",
          details: "Based on a five-member household, the per capita annual carbon emission is approximately 8.22 tons of CO₂e — more than four times the UN 2030 target of 2 tons per capita. This figure exceeds both the China country average and the world average. Food (43%) and transportation (34%) are the dominant sources.",
        },
        after: {
          total: "21.93",
          perCapita: "4.39",
          details: "After implementing the 4R actions and reducing car use by 5,000 km annually, cutting flights to 3 per year, and shifting to a more plant-based diet, household emissions fell from 41.12 to 21.93 tons. Transportation emissions dropped by nearly 50% through reduced fossil fuel use. These actions are highly replicable and practical for most households.",
        },
      },
      coBenefits: [
        { title: "Financial Savings", desc: "Extending the lifecycle of items and avoiding unnecessary purchases can lower expenditure on goods, subsequently cutting down the cost of living." },
        { title: "Biodiversity and Ecosystem Protection", desc: "Decreasing demand for raw materials lessens the destruction caused by mining, logging, and manufacturing, helping preserve natural habitats." },
        { title: "Public Health Improvements", desc: "Cutting down plastic use lowers exposure to harmful chemicals, while less waste means fewer pollutants released into the environment from incineration and landfill." },
        { title: "Circular Economy Promotion", desc: "This action supports a shift from the linear 'take-make-waste' model to a circular economy (UNDP, n.d.), decreasing waste and improving resource efficiency." },
        { title: "Education and Social Impacts", desc: "Practising these habits helps foster sustainable awareness towards consumption, which aligns with SDG 4 and encourages others to adopt a low-carbon lifestyle." },
      ],
      offsetSolutions: [
        {
          title: "Finance certified recycling and material recovery",
          desc: "After reducing purchases, I would offset unavoidable product emissions by supporting certified recycling, textile recovery, or e-waste collection projects that prevent new raw-material extraction and save equivalent emissions.",
          evidence: "Add a member head shot sorting recyclables or delivering e-waste.",
        },
        {
          title: "Donate to repair and reuse programmes",
          desc: "Repair cafes, second-hand libraries, and community reuse projects reduce demand for new production. Funding or volunteering in these projects can compensate for the remaining emissions attached to products I still need to buy.",
          evidence: "Add a member head shot repairing clothing, books, electronics, or stationery.",
        },
        {
          title: "Buy verified circular products for unavoidable purchases",
          desc: "When purchasing is unavoidable, I would choose products with credible recycled content, durability, and repairability claims. This shifts spending toward lower-carbon supply chains and offsets part of the impact of consumption.",
          evidence: "Add a member head shot with a repaired or second-hand item.",
        },
      ],
    },
  ],
  references: [
    "Britannica Editors. (2026, May 5). Carbon dioxide. Retrieved from Britannica: https://www.britannica.com/science/carbon-dioxide",
    "Climate Change Tracker. (2024). China's Progress and Recent Impact. https://climatechangetracker.org/nations/greenhouse-gas-emissions/china/progress-and-recent-impact",
    "FasterCapital. (2025, April 9). Bike Environmental Impact: Biking vs. Public Transportation: Which Is Better for the Planet. https://fastercapital.com/content/Bike-Environmental-Impact--Biking-vs--Public-Transportation--Which-Is-Better-for-the-Planet.html",
    "Green.Earth. (n.d.). Understanding carbon footprints: impact, benefits, and reporting. https://www.green.earth/carbonfootprints",
    "Hilton, I. (2026, March 26). As It Boosts Renewables, China Still Can't Break Its Coal Addiction. Yale School of the Environment: https://e360.yale.edu/features/china-coal-five-year-plan",
    "Hodges, M. (2025, October 13). Eco-Friendly Commutes: Walking And Biking's Impact On Our Planet. SHUN WASTE: https://shunwaste.com/article/how-does-walking-or-riding-a-bike-affect-the-environment",
    "Nations, United. (n.d.). Actions for a healthy planet. United Nations: https://www.un.org/en/actnow/ten-actions",
    "Scells, H., Zhuang, S., & Zuccon, G. (2022). Reduce, Reuse, Recycle: Green Information Retrieval Research. Proceedings of the 45th ACM SIGIR Conference. https://doi.org/10.1145/3477495.3531738",
    "TheGlobalEconomy. (2023). China: Coal Reserves. https://www.theglobaleconomy.com/China/coal_reserves/",
    "United Nation. (2015, September 25). Department of Economic and Social Affairs. Sustainable Development: https://sdgs.un.org/goals/goal13#targets_and_indicators",
    "United Nations. (n.d.). Actions for a healthy planet. Retrieved from: https://un.org/en/actnow/ten-actions",
    "United Nations Development Programme. (n.d.). A circular economy aligns environmental protection with long-term economic and social well-being. Retrieved from: https://www.undp.org/chemicals-waste/our-work/circular-economy",
    "Wang, J., Huang, J., Rozelle, S. (2010, May 1). Climate Change and China's Agricultural Sector: Impacts, Adaptation, and Mitigation. Stanford University: https://aparc.fsi.stanford.edu/publications/climate_change_and_chinas_agricultural_sector_impacts_adaptation_and_mitigation",
  ],
};
