export const sdgDetails = {
  4: {
    number: "SDG 4",
    title: "Quality Education",
    subtitle: "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.",
    color: "from-red-400/20 to-red-500/10",
    borderColor: "border-red-400/30",
    textColor: "text-red-200/80",
    heroGradient: "radial-gradient(circle_at_50%_30%,rgba(248,113,113,0.18)_0%,rgba(248,113,113,0.06)_40%,transparent_70%)",
    heroImage: "/images/sdg4/image1.png",
    overview:
      "SDG 4 aims to ensure inclusive and equitable quality education and promote lifelong learning opportunities for all (United Nations Department of Economic and Social Affairs, n.d.). Education is regarded as a key driver for poverty elimination, gender equality, and sustainable development. Quality education is a core enabler in empowering individuals to participate in society completely (UNESCO, 2026).",
    targets: [
      "By 2030, ensure all girls and boys complete free, equitable, and quality primary and secondary education",
      "Ensure all girls and boys have access to quality early childhood development and pre-primary education",
      "Equal access to affordable technical, vocational, and higher education for all women and men",
      "Eliminate gender disparities in education and ensure equal access for the vulnerable",
      "Universal literacy and numeracy among youth and a substantial proportion of adults",
      "Education for sustainable development and global citizenship",
    ],
    facts: [
      "The retention rate of nine-year compulsory education in China reached 95.9% in 2024, but 4.1% of students still fail to graduate (Ministry of Education, 2025).",
      "Economically developed regions in China receive significantly more education funding than remote rural areas due to industrial agglomeration and higher fiscal revenues.",
      "During the pandemic, some rural students had to walk kilometres to find an internet signal for online classes, exposing deep digital divides.",
      "In Yunnan province, children walk hours on unsafe paths and bridges just to get to school each day.",
      "Many elderly people in rural China cannot use smartphones to access learning apps, restricting their potential for digital lifelong learning.",
    ],
    connections: "Quality education underpins progress across most other SDGs. Better-educated populations make more informed health choices (SDG 3), are more likely to adopt sustainable consumption habits (SDG 12) and climate action (SDG 13), and drive economic growth that reduces poverty (SDG 1) and inequality (SDG 10). Education also strengthens civic participation and institution-building (SDG 16).",
    richSections: [
      {
        id: "education-challenges",
        label: "Education Challenges in China",
        type: "challenges",
        intro: "Despite immense advancement in education, China still faces persistent issues in achieving SDG 4. Rural students, left-behind children, children of migrant workers, students with disabilities, and the elderly all face barriers. Teachers in under-resourced regions work with limited support, and government departments must invest more to close the gaps between regions.",
        challenges: [
          {
            title: "Regional Education Imbalance",
            image: "/images/sdg4/image2.jpeg",
            imageCaption: "Source: Leadership Society of Arizona — Issues of China education system",
            content: "Economically developed areas, such as major cities and special economic zones, benefit from industrial agglomeration effects and higher fiscal revenues, allowing them to receive significantly more education funding (Huang, 2024). Well-developed regions enjoy sufficient funding, advanced teaching facilities, and knowledgeable teachers. However, economically developing areas, like remote villages, lack all these resources. As a result, these poorer regions are unlikely to provide diverse and high-quality education for students.",
          },
          {
            title: "Disadvantaged Groups and Unequal Access",
            image: "/images/sdg4/image3.jpeg",
            imageCaption: "Source: BTIME Report — Challenges in Yunnan's rural education",
            content: "Unequal educational chances for disadvantaged groups stem from systemic factors including family poverty, geographic isolation, and lack of parental care. Many low-income students cannot afford tuition fees and are more likely to drop out of school due to inconvenient access, high family education expenditure, and lack of parental companionship. The retention rate of nine-year compulsory education is 95.9%, but 4.1% of students are still unable to graduate (Ministry of Education of the People's Republic of China, 2025). In Yunnan province, children walk hours on unsafe paths such as bridges to go to school.",
          },
          {
            title: "Inadequate Lifelong Learning",
            image: "/images/sdg4/image4.png",
            imageCaption: "Source: China Daily — More nuanced approach to aging needed",
            content: "The popularisation of lifelong learning remains inadequate, primarily due to limited public funding for adult education and low penetration rates of digital learning platforms. Rural adults often have no access to literacy classes or vocational training. For instance, many seniors cannot use smartphones to access learning apps, which restricts their potential abilities in digital lifelong learning and excludes them from the knowledge economy.",
          },
          {
            title: "The Digital Divide",
            image: "/images/sdg4/image5.png",
            imageCaption: "Source: CGTN — Shanghai to resume in-person classes",
            content: "Online education has become a crucial trend; nevertheless, it also widens new gaps. Urban students are equipped with stable internet, personal devices, and comprehensive digital resources. However, rural students lack even basic resources. During the pandemic, some had to walk kilometres to find a signal. This digital divide not only undermines education equality but also slows progress toward SDG 4, creating a two-tier system where technology amplifies existing inequalities rather than bridging them.",
          },
        ],
      },
      {
        id: "personal-solutions",
        label: "Personal Solutions",
        type: "challenges",
        intro: "With the aim of addressing these challenges and advancing SDG 4 in China, as a university student, I propose several feasible solutions that can be implemented at the individual level.",
        challenges: [
          {
            title: "Tutoring Programmes for Rural Students",
            image: "/images/sdg4/image6.png",
            imageCaption: "Source: Class Central — List of Chinese Online Course Platforms in 2026",
            content: "Everyone should actively participate in tutoring programmes for rural students, principally concentrating on improving their digital literacy skills. Leading weekly online classes to impart basic digital skills will be conducive to narrowing the existing education gap. University students can volunteer their time to provide one-on-one mentoring through existing online education platforms, helping bridge the resource divide between urban and rural schools.",
          },
          {
            title: "Curriculum and Assessment Reform",
            image: "/images/sdg4/image7.png",
            imageCaption: "Source: New GCSE Curriculum Review 2026 — Preparation Guide",
            content: "Revising curricula and assessment systems is integral to improving education quality. Schools can include various practical tasks in regular evaluation, involving collaborative projects, internet use assessment, and basic critical thinking tests. Moving beyond rote memorisation toward skills-based, project-driven learning better prepares students for the modern workforce and fosters the creativity needed for sustainable development.",
          },
          {
            title: "Lifelong Learning and Vocational Education",
            image: "/images/sdg4/image8.png",
            imageCaption: "Source: Wuxi Agricultural and Rural Bureau — Jiangyin youth rural classroom report",
            content: "Advocating for lifelong learning and vocational education is essential. More information about professional opportunities and the significance of perpetual learning need to reach the wider population. Lectures held by professionals can help students explore diverse career paths, while community-based adult education programmes can ensure that learning does not stop after formal schooling ends. This is particularly important for rural adults and the elderly who have been left behind by rapid technological change.",
          },
        ],
      },
      {
        id: "references",
        label: "References",
        type: "references",
        references: [
          "Huang, X. (2024). Research on the Formation and Evolution Mechanism of the Urban-Rural Education Gap in China. Academic Journal of Humanities & Social Sciences, 7(7), 152-157. https://doi.org/10.25236/AJHSS.2024.070723",
          "Ministry of Education of the People's Republic of China. (2025). 2024 national education development statistical bulletin.",
          "United Nations Department of Economic and Social Affairs. (n.d.). Goal 4: Ensure inclusive and equitable quality education. Retrieved from: https://sdgs.un.org/goals/goal4",
          "United Nations Educational, Scientific and Cultural Organization (UNESCO). (2026). Higher education global trends report: Towards inclusive, equitable and quality higher education in an internationally mobile landscape.",
        ],
      },
    ],
  },
  13: {
    number: "SDG 13",
    title: "Climate Action",
    subtitle: "Take urgent action to combat climate change and its impacts across all sectors of society.",
    color: "from-emerald-400/20 to-green-500/10",
    borderColor: "border-emerald-400/30",
    textColor: "text-emerald-200/80",
    heroGradient: "radial-gradient(circle_at_50%_30%,rgba(52,211,153,0.18)_0%,rgba(52,211,153,0.06)_40%,transparent_70%)",
    heroImage: "/images/sdg13/image1.png",
    overview:
      "Climate change is one of the defining challenges of our time. SDG 13 calls for urgent action to combat climate change and its impacts (United Nation, 2015). By 2030, all countries are required to comprehensively improve their capacity to resist and adapt to extreme climate disasters. Climate governance shall be integrated into national development planning, with corresponding capital and technological investment, so as to jointly mitigate various risks and hazards arising from global warming.",
    targets: [
      "Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries",
      "Integrate climate change measures into national policies, strategies, and planning",
      "Improve education, awareness-raising, and institutional capacity on climate change mitigation and adaptation",
      "Implement the UNFCCC commitment of $100 billion annually by developed countries",
      "Promote mechanisms for raising capacity for effective climate planning in least developed countries",
    ],
    facts: [
      "China's total carbon emissions accounted for approximately 25.6% of the global total in 2024, with coal contributing the majority (Climate Change Tracker, 2024).",
      "Greenhouse gas emissions must decline 43% by 2030 to limit warming to 1.5°C above pre-industrial levels.",
      "Global average temperatures in 2024 were approximately 1.55°C above pre-industrial levels.",
      "Climate-related disasters have increased by 83% over the past 20 years.",
      "The cost of renewable energy (solar, wind) has dropped 80–90% over the past decade.",
    ],
    connections: "Climate action is deeply interconnected with every SDG. Rising temperatures threaten food security (SDG 2), exacerbate health risks (SDG 3), worsen water scarcity (SDG 6), and disrupt economic growth (SDG 8). Transitioning to clean energy (SDG 7) and building sustainable cities (SDG 11) are essential climate mitigation strategies.",
    richSections: [
      {
        id: "china-challenges",
        label: "China's Climate Challenges",
        type: "challenges",
        intro: "China faces complex and interconnected climate challenges driven by its energy structure, rapid development, agricultural practices, and natural climate variability. Understanding these adverse impacts is essential to formulating effective responses.",
        challenges: [
          {
            title: "Coal Dependence in Energy Structure",
            image: "/images/sdg13/image2.png",
            imageCaption: "Source: Climate Change Tracker",
            content: "One of the core causes of China's climate challenge is the sustained high emissions resulting from the long-standing coal-dominated energy structure. China possesses abundant coal reserves with low extraction costs, reaching 173,107.86 million short tons in 2023 (TheGlobalEconomy, 2023). In 2024, China's total carbon emissions accounted for approximately 25.6% of the global total, with coal contributing the majority of this volume (Climate Change Tracker, 2024). Although decades of investment in renewable energy technology and manufacturing in China have yielded remarkable outcomes, this success has not been effectively translated into substantial reductions in greenhouse gas emissions due to the sustained dependence on coal (Hilton, 2026).",
            secondaryImage: "/images/sdg13/image3.png",
            secondaryCaption: "Source: Yale E360 — As It Boosts Renewables, China Still Can't Break Its Coal Addiction",
          },
          {
            title: "Industrialization & Urbanization",
            image: "/images/sdg13/image4.jpeg",
            imageCaption: "Source: CGTN — China's Urbanization 2021",
            content: "The combined effects of industrialization and urbanization have further intensified climate issues. In the industrial sector, fundamental industries such as steel and cement serve as pillars of the economy. These industries not only rely on coal for heat supply, but coal also remains irreplaceable in certain production processes. Accelerated urbanization alters land surface characteristics, thereby affecting regional climates. The increasing proportion of impervious surfaces in cities has led to higher temperatures in urban centers compared to suburbs, making the urban heat island effects increasingly prominent. Meanwhile, expanding cities continue to encroach upon ecological spaces such as forests and wetlands, resulting in a continuous decline in carbon sequestration capacity.",
          },
          {
            title: "Agricultural Activities",
            image: "/images/sdg13/image5.jpg",
            imageCaption: "Source: Agriculture Monthly",
            content: "Agricultural production also affects the climate. Livestock farming, rice cultivation, and fertilizer application release greenhouse gases including methane and nitrous oxide. The warming effect of these two gases is far greater than that of carbon dioxide. Fertilizers are the primary source of nitrous oxide emissions and have become a major cause of water pollution. The continuous accumulation of large volumes of potent greenhouse gases intensifies the greenhouse effect and exacerbates climate anomalies (Wang, Huang & Rozelle, 2010).",
          },
          {
            title: "Natural Variability",
            image: "/images/sdg13/image6.jpeg",
            imageCaption: "Source: Global Times — El Nino will lead to more extreme weather for China",
            content: "Although natural variability is not the primary cause, it has exacerbated the impacts of human-induced emissions. The El Nino event led to a 1.2-degree Celsius increase in sea surface temperatures in the central and eastern equatorial Pacific. This directly triggered summer heatwaves and droughts in northern China, while southern regions experienced extreme rainfall and flooding, affecting drinking water supplies, agricultural irrigation, industrial production, and urban water systems.",
          },
        ],
      },
      {
        id: "references",
        label: "References",
        type: "references",
        references: [
          "Climate Change Tracker. (2024). China's Progress and Recent Impact. https://climatechangetracker.org/nations/greenhouse-gas-emissions/china/progress-and-recent-impact",
          "Hilton, I. (2026, March 26). As It Boosts Renewables, China Still Can't Break Its Coal Addiction. Yale School of the Environment: https://e360.yale.edu/features/china-coal-five-year-plan",
          "TheGlobalEconomy. (2023). China: Coal Reserves. https://www.theglobaleconomy.com/China/coal_reserves/",
          "United Nation. (2015, September 25). Department of Economic and Social Affairs. Sustainable Development: https://sdgs.un.org/goals/goal13#targets_and_indicators",
          "Wang, J., Huang, J., Rozelle, S. (2010, May 1). Climate Change and China's Agricultural Sector: Impacts, Adaptation, and Mitigation. Stanford University: https://aparc.fsi.stanford.edu/publications/climate_change_and_chinas_agricultural_sector_impacts_adaptation_and_mitigation",
        ],
      },
    ],
  },
  3: {
    number: "SDG 3",
    title: "Good Health and Well-being",
    subtitle: "Ensure healthy lives and promote well-being for all at all ages.",
    color: "from-rose-400/20 to-pink-500/10",
    borderColor: "border-rose-400/30",
    textColor: "text-rose-200/80",
    heroGradient: "radial-gradient(circle_at_50%_30%,rgba(251,113,133,0.18)_0%,rgba(251,113,133,0.06)_40%,transparent_70%)",
    overview:
      "Good health is essential to human welfare and to sustained economic and social development. SDG 3 aims to ensure universal health coverage, reduce maternal and child mortality, end epidemics of communicable diseases, and strengthen the capacity of all countries for early warning and health risk management.",
    targets: [
      "Reduce global maternal mortality ratio to less than 70 per 100,000 live births",
      "End preventable deaths of newborns and children under 5 years of age",
      "End the epidemics of AIDS, tuberculosis, malaria, and neglected tropical diseases",
      "Reduce premature mortality from non-communicable diseases by one third by 2030",
      "Achieve universal health coverage, including financial risk protection and access to essential services",
      "Strengthen the implementation of the WHO Framework Convention on Tobacco Control",
    ],
    facts: [
      "Global life expectancy reached 73.4 years in 2024 but varies by over 30 years between countries.",
      "Over 5 million children died before their fifth birthday in 2023, mostly from preventable causes.",
      "Universal health coverage could avert 300 million cases of catastrophic health expenditure annually.",
      "The global suicide rate is approximately 9 per 100,000 people — one death every 40 seconds.",
      "Mental health conditions affect 1 in 8 people globally, yet funding remains critically low.",
    ],
    connections: "Health is both a driver and an outcome of sustainable development. Poverty (SDG 1) limits access to healthcare. Clean water (SDG 6) and sanitation prevent disease. Air pollution from energy use (SDG 7) causes 7 million premature deaths annually. Education (SDG 4) improves health literacy and outcomes.",
  },
  16: {
    number: "SDG 16",
    title: "Peace, Justice and Strong Institutions",
    subtitle: "Promote peaceful and inclusive societies for sustainable development, provide access to justice for all, and build effective, accountable institutions.",
    color: "from-blue-400/20 to-indigo-500/10",
    borderColor: "border-blue-400/30",
    textColor: "text-blue-200/80",
    heroGradient: "radial-gradient(circle_at_50%_30%,rgba(96,165,250,0.18)_0%,rgba(96,165,250,0.06)_40%,transparent_70%)",
    overview:
      "Peace, stability, human rights, and effective governance are fundamental prerequisites for sustainable development. SDG 16 aims to reduce violence, end abuse and exploitation of children, promote the rule of law, combat corruption, and ensure public access to information and participation in decision-making.",
    targets: [
      "Significantly reduce all forms of violence and related death rates everywhere",
      "End abuse, exploitation, trafficking, and all forms of violence against children",
      "Promote the rule of law at the national and international levels and ensure equal access to justice",
      "Significantly reduce illicit financial and arms flows and combat organized crime",
      "Substantially reduce corruption and bribery in all their forms",
      "Ensure responsive, inclusive, participatory, and representative decision-making",
    ],
    facts: [
      "Over 450 million children live in conflict-affected zones as of 2024.",
      "Corruption costs the global economy an estimated $3.6 trillion annually — 5% of global GDP.",
      "Approximately 1.5 billion people worldwide have unmet justice needs.",
      "Only 26% of national parliamentarians worldwide are women.",
      "Strong rule of law is correlated with a 20-30% higher GDP per capita in developing countries.",
    ],
    connections: "Peace and justice are foundational enablers for the entire SDG framework. Conflict destroys infrastructure (SDG 9), displaces communities from homes (SDG 11), disrupts food systems (SDG 2), and prevents children from attending school (SDG 4). Without accountable institutions, investments in health, education, and climate all face systemic barriers.",
  },
};
